### ISSUE TITLE
Help with packaging `sphinx-changelog` for `conda-forge`

### ISSUE THREAD

**Issue by BSGalvan** [OpenAstronomy/sphinx-changelog#15]
I am working on writing a recipe for `sphinx-changelog` to get it into `conda-forge`.

It would be really helpful if any of the package devs could jump on as a maintainer for the `conda-forge` recipe. 
Once tests get written here, I will need someone who knows the nitty-gritty of the testing process, to help include testing for the `conda-forge` recipe.
Plus, it would be best to have a second set of eyes as well!

You can see the (draft) PR [here](https://github.com/conda-forge/staged-recipes/pull/20661).
Thanks for the awesome software!

**Comment by Cadair** [comment]
hey @BSGalvan Thanks for the ping, I am happy to help.

**Comment by BSGalvan** [comment]
Awesome! Thanks for the quick response :D
