### ISSUE TITLE
Unpin towncrier and importlib-resources

### ISSUE THREAD

**Issue by nabobalis** [OpenAstronomy/sphinx-changelog#22]
Towncrier fixed this in their newer releases but this plugin still pins to an older version.

Could we get an update? I can do a PR if needed.

**Comment by Cadair** [comment]
The hard pin on towncrier is deliberate because we rely on internal API and it loves to break. I thought I had configured dependabot to automatically open a bump PR, but apparently not properly.

**Comment by nabobalis** [comment]
Any chance of a bump to https://github.com/twisted/towncrier/releases/tag/23.11.0 at least to see if this plugin still works?
